name: packageproxy
version: 0.1
summary: approx based package proxy running on port 9999
description: approx based package proxy
confinement: strict

apps:
  approx:
    command: run-approx
    daemon: simple
    plugs: [network, network-bind]

parts:
  fixpaths:
    source: .
    plugin: make
    build-packages:
      - debhelper
      - dh-ocaml
      - fakeroot
      - libnethttpd-ocaml-dev
      - libpcre-ocaml-dev
      - libsha-ocaml-dev
      - ocaml-nox
  approx:
    plugin: copy
    files:
        run-approx: run-approx
        config.yaml: config.yaml
        config.sh: config.sh
    stage-packages:
      - bzip2
      - curl
      - gawk
      - gzip
      - sed
      - socat
      - xz-utils
    after: [fixpaths]
